### ISSUE TITLE
First example doesn't work for me

### ISSUE THREAD

**Issue by theslyprofessor** [midival/core#11]
I get this error: ×
TypeError: Cannot read properties of undefined (reading 'connect')
MidiMonitor
src/Pages/MidiInput/components/MidiMonitor.js:6
  3 | 
  4 | 
  5 | function MidiMonitor() {
> 6 |   MIDIVal.connect()
  7 |   .then(accessObject => {
  8 |       console.log("Inputs", accessObject.inputs)
  9 |       console.log("Outputs", accessObject.outputs)

**Comment by kulak-at** [comment]
Hi, you are right. The example didn't work because of wrong import. Fix first line to `import { MIDIVal } from "@midival/core"` and it should do the trick. I've fixed it in readme.

Thanks for testing it!
