### ISSUE TITLE
React Native yarn add @midival/native can't be found or installed

### ISSUE THREAD

**Issue by elmcapp** [midival/core#15]
when running yarn add @midival/native I get the following error

error An unexpected error occurred: "https://registry.yarnpkg.com/@midival%2fnative: Not found".

**Comment by kulak-at** [comment]
Hey,
I've published react-native adapter a few days ago, the package is called `@midival/react-native`. Feel free to test it, it's in the experimental state currently. I've tested iOS version and it works fine, need to do more tests for Android soon. Feel free to contribute too :)

**Comment by elmcapp** [comment]
Thanks.
