### ISSUE TITLE
Does it also support dial knobs and sliders?

### ISSUE THREAD

**Issue by Nukron** [midival/core#17]
I tested the midival/core with an react application and it can read all my input pads, how ever there is no message appearing when i start to use my knob dials or sliders on my midi. Is this something that will be added in the future?

Best regards and amazing project!

**Comment by kulak-at** [comment]
I see you've already closed the issue, I hope you found the answer yourself. For sliders and dials you can [use `onAllControlChange` hook ](https://midival.github.io/core/classes/MIDIValInput.html#onAllControlChange). I hope that helps :)
